#!/bin/bash

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -C "Generated RSA key pair" -f $KEY_NAME -N $PASSPHRASE

# Provide feedback to the user
echo "RSA key pair generated successfully."
