#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6888-web
    bind *:80
    mode http
    balance roundrobin
    server 6888-web-01 3.91.179.247:80 check
    server 6888-web-02 52.54.244.240:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
