#!/usr/bin/env bash
# Script that installs and configures Nginx to serve "Holberton School"

# Update packages
apt-get update -y && apt-get upgrade -y

# Install nginx
apt-get install nginx -y

# Start nginx service
service nginx start

# Replace the default index.html with required content
echo "Holberton School" > /usr/share/nginx/html/index.html
